name: test

on:
  pull_request:
    types: [opened, review_requested, ready_for_review, synchronize]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Validate lockfile
        run: npm install --package-lock-only && git diff --exit-code package-lock.json

      - name: Check formatting
        run: npm run format:check

      - name: Run tests
        run: npm run test

      - name: Type check
        run: npx tsc
